
### 

curl -X GET https://<yout_adb_host>/api/2.0/preview/sql/data_sources \
--header "Content-Type: application/json" \
--header "Authorization: Bearer <yout_adb_token>"

### 

curl -X GET https://<yout_adb_host>/api/2.1/jobs/list \
--header "Content-Type: application/json" \
--header "Authorization: Bearer <yout_adb_token>"

### 

curl -X POST https://<yout_adb_host>/api/2.0/sql/statements \
--header "Content-Type: application/json" \
--header "Authorization: Bearer <yout_adb_token>" \
--data '{
  "warehouse_id" : "",
  "cluster_id": "3775820491380537",
  "catalog": "bronze",
  "schema": "bronze",
  "statement": "SELECT * FROM dev_catalog.bronze.raw_roads LIMIT 10"
}'
